name: Release Plugin

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Package
        run: |
          mkdir -p release
          cp main.js manifest.json styles.css release/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/main.js
            release/manifest.json
            release/styles.css
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
